// Code generated by protoc-gen-go. DO NOT EDIT.
// source: access.proto

package command

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRet int32

const (
	AuthRet_AUTH_OK   AuthRet = 0
	AuthRet_NO_TYPE   AuthRet = 1
	AuthRet_NO_SERVER AuthRet = 2
	AuthRet_KEY_ERROR AuthRet = 3
)

var AuthRet_name = map[int32]string{
	0: "AUTH_OK",
	1: "NO_TYPE",
	2: "NO_SERVER",
	3: "KEY_ERROR",
}

var AuthRet_value = map[string]int32{
	"AUTH_OK":   0,
	"NO_TYPE":   1,
	"NO_SERVER": 2,
	"KEY_ERROR": 3,
}

func (x AuthRet) String() string {
	return proto.EnumName(AuthRet_name, int32(x))
}

func (AuthRet) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{0}
}

type LoginRet int32

const (
	LoginRet_LOGIN_OK              LoginRet = 0
	LoginRet_LOGIN_KEY_ERROR       LoginRet = 1
	LoginRet_LOGIN_IN_OTHER_GAME   LoginRet = 2
	LoginRet_LOGIN_IN_OTHER_SERVER LoginRet = 3
	LoginRet_LOGIN_ACCOUNT_ERROR   LoginRet = 4
	LoginRet_LOGIN_ACCOUNT_BLOCKED LoginRet = 5
	LoginRet_LOGIN_TABLE_ERROR     LoginRet = 6
	LoginRet_LOGIN_TYPE_ERROR      LoginRet = 7
	LoginRet_LOGIN_IN_OTHER_SLOT   LoginRet = 8
	LoginRet_LOGIN_LANGUAGE_ERROR  LoginRet = 9
)

var LoginRet_name = map[int32]string{
	0: "LOGIN_OK",
	1: "LOGIN_KEY_ERROR",
	2: "LOGIN_IN_OTHER_GAME",
	3: "LOGIN_IN_OTHER_SERVER",
	4: "LOGIN_ACCOUNT_ERROR",
	5: "LOGIN_ACCOUNT_BLOCKED",
	6: "LOGIN_TABLE_ERROR",
	7: "LOGIN_TYPE_ERROR",
	8: "LOGIN_IN_OTHER_SLOT",
	9: "LOGIN_LANGUAGE_ERROR",
}

var LoginRet_value = map[string]int32{
	"LOGIN_OK":              0,
	"LOGIN_KEY_ERROR":       1,
	"LOGIN_IN_OTHER_GAME":   2,
	"LOGIN_IN_OTHER_SERVER": 3,
	"LOGIN_ACCOUNT_ERROR":   4,
	"LOGIN_ACCOUNT_BLOCKED": 5,
	"LOGIN_TABLE_ERROR":     6,
	"LOGIN_TYPE_ERROR":      7,
	"LOGIN_IN_OTHER_SLOT":   8,
	"LOGIN_LANGUAGE_ERROR":  9,
}

func (x LoginRet) String() string {
	return proto.EnumName(LoginRet_name, int32(x))
}

func (LoginRet) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{1}
}

type LogoutRet int32

const (
	LogoutRet_UNKNOWN2       LogoutRet = 0
	LogoutRet_LOGOUT_OK      LogoutRet = 1
	LogoutRet_LOGOUT_OFFLINE LogoutRet = 2
	LogoutRet_LOGOUT_UPDATE  LogoutRet = 3
	LogoutRet_LOGOUT_KICK    LogoutRet = 4
	LogoutRet_LOGOUT_CHIP    LogoutRet = 5
)

var LogoutRet_name = map[int32]string{
	0: "UNKNOWN2",
	1: "LOGOUT_OK",
	2: "LOGOUT_OFFLINE",
	3: "LOGOUT_UPDATE",
	4: "LOGOUT_KICK",
	5: "LOGOUT_CHIP",
}

var LogoutRet_value = map[string]int32{
	"UNKNOWN2":       0,
	"LOGOUT_OK":      1,
	"LOGOUT_OFFLINE": 2,
	"LOGOUT_UPDATE":  3,
	"LOGOUT_KICK":    4,
	"LOGOUT_CHIP":    5,
}

func (x LogoutRet) String() string {
	return proto.EnumName(LogoutRet_name, int32(x))
}

func (LogoutRet) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{2}
}

type RegisterServer struct {
	Sid                  int32    `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Tid                  int32    `protobuf:"varint,3,opt,name=tid,proto3" json:"tid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServer) Reset()         { *m = RegisterServer{} }
func (m *RegisterServer) String() string { return proto.CompactTextString(m) }
func (*RegisterServer) ProtoMessage()    {}
func (*RegisterServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{0}
}

func (m *RegisterServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServer.Unmarshal(m, b)
}
func (m *RegisterServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServer.Marshal(b, m, deterministic)
}
func (m *RegisterServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServer.Merge(m, src)
}
func (m *RegisterServer) XXX_Size() int {
	return xxx_messageInfo_RegisterServer.Size(m)
}
func (m *RegisterServer) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServer.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServer proto.InternalMessageInfo

func (m *RegisterServer) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *RegisterServer) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RegisterServer) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

type LoginAuthReq struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid                  int32    `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Sid                  int32    `protobuf:"varint,3,opt,name=sid,proto3" json:"sid,omitempty"`
	Version              int32    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	MtKey                string   `protobuf:"bytes,5,opt,name=mtKey,proto3" json:"mtKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAuthReq) Reset()         { *m = LoginAuthReq{} }
func (m *LoginAuthReq) String() string { return proto.CompactTextString(m) }
func (*LoginAuthReq) ProtoMessage()    {}
func (*LoginAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{1}
}

func (m *LoginAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAuthReq.Unmarshal(m, b)
}
func (m *LoginAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAuthReq.Marshal(b, m, deterministic)
}
func (m *LoginAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAuthReq.Merge(m, src)
}
func (m *LoginAuthReq) XXX_Size() int {
	return xxx_messageInfo_LoginAuthReq.Size(m)
}
func (m *LoginAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAuthReq proto.InternalMessageInfo

func (m *LoginAuthReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginAuthReq) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *LoginAuthReq) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *LoginAuthReq) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *LoginAuthReq) GetMtKey() string {
	if m != nil {
		return m.MtKey
	}
	return ""
}

type LoginAuthRes struct {
	Ret                  AuthRet  `protobuf:"varint,1,opt,name=ret,proto3,enum=command.AuthRet" json:"ret,omitempty"`
	Sid                  int32    `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Version              int32    `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAuthRes) Reset()         { *m = LoginAuthRes{} }
func (m *LoginAuthRes) String() string { return proto.CompactTextString(m) }
func (*LoginAuthRes) ProtoMessage()    {}
func (*LoginAuthRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{2}
}

func (m *LoginAuthRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAuthRes.Unmarshal(m, b)
}
func (m *LoginAuthRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAuthRes.Marshal(b, m, deterministic)
}
func (m *LoginAuthRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAuthRes.Merge(m, src)
}
func (m *LoginAuthRes) XXX_Size() int {
	return xxx_messageInfo_LoginAuthRes.Size(m)
}
func (m *LoginAuthRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAuthRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAuthRes proto.InternalMessageInfo

func (m *LoginAuthRes) GetRet() AuthRet {
	if m != nil {
		return m.Ret
	}
	return AuthRet_AUTH_OK
}

func (m *LoginAuthRes) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *LoginAuthRes) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type LoginReq struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	MtKey                string   `protobuf:"bytes,3,opt,name=mtKey,proto3" json:"mtKey,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{3}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *LoginReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginReq) GetMtKey() string {
	if m != nil {
		return m.MtKey
	}
	return ""
}

func (m *LoginReq) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type LoginRes struct {
	Ret                  LoginRet `protobuf:"varint,1,opt,name=ret,proto3,enum=command.LoginRet" json:"ret,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Money                int64    `protobuf:"varint,3,opt,name=money,proto3" json:"money,omitempty"`
	Cheque               int64    `protobuf:"varint,4,opt,name=cheque,proto3" json:"cheque,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{4}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetRet() LoginRet {
	if m != nil {
		return m.Ret
	}
	return LoginRet_LOGIN_OK
}

func (m *LoginRes) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginRes) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *LoginRes) GetCheque() int64 {
	if m != nil {
		return m.Cheque
	}
	return 0
}

type LogoutRes struct {
	Ret                  LogoutRet `protobuf:"varint,1,opt,name=ret,proto3,enum=command.LogoutRet" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogoutRes) Reset()         { *m = LogoutRes{} }
func (m *LogoutRes) String() string { return proto.CompactTextString(m) }
func (*LogoutRes) ProtoMessage()    {}
func (*LogoutRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a098e900d2c3a6f2, []int{5}
}

func (m *LogoutRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRes.Unmarshal(m, b)
}
func (m *LogoutRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRes.Marshal(b, m, deterministic)
}
func (m *LogoutRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRes.Merge(m, src)
}
func (m *LogoutRes) XXX_Size() int {
	return xxx_messageInfo_LogoutRes.Size(m)
}
func (m *LogoutRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRes.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRes proto.InternalMessageInfo

func (m *LogoutRes) GetRet() LogoutRet {
	if m != nil {
		return m.Ret
	}
	return LogoutRet_UNKNOWN2
}

func init() {
	proto.RegisterEnum("command.AuthRet", AuthRet_name, AuthRet_value)
	proto.RegisterEnum("command.LoginRet", LoginRet_name, LoginRet_value)
	proto.RegisterEnum("command.LogoutRet", LogoutRet_name, LogoutRet_value)
	proto.RegisterType((*RegisterServer)(nil), "command.RegisterServer")
	proto.RegisterType((*LoginAuthReq)(nil), "command.LoginAuthReq")
	proto.RegisterType((*LoginAuthRes)(nil), "command.LoginAuthRes")
	proto.RegisterType((*LoginReq)(nil), "command.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "command.LoginRes")
	proto.RegisterType((*LogoutRes)(nil), "command.LogoutRes")
}

func init() { proto.RegisterFile("access.proto", fileDescriptor_a098e900d2c3a6f2) }

var fileDescriptor_a098e900d2c3a6f2 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4f, 0x6f, 0xda, 0x30,
	0x18, 0xc6, 0x1b, 0x5c, 0x0a, 0xbc, 0xa5, 0xd4, 0xb8, 0x74, 0xcb, 0x76, 0xaa, 0xb2, 0x1d, 0x2a,
	0x0e, 0x48, 0xeb, 0x3e, 0x41, 0x4a, 0x53, 0x40, 0xc9, 0x62, 0x64, 0x92, 0x4d, 0x5c, 0xc6, 0x18,
	0x58, 0x34, 0xd2, 0x20, 0x23, 0x71, 0x2a, 0xed, 0x83, 0xef, 0x3e, 0x39, 0x76, 0x12, 0x98, 0xb8,
	0xe5, 0x79, 0xff, 0xfd, 0x9e, 0xc7, 0x52, 0xa0, 0xbd, 0x5c, 0xad, 0x78, 0x9a, 0x0e, 0x7e, 0x27,
	0xb1, 0x88, 0x49, 0x63, 0x15, 0x6f, 0xb7, 0xcb, 0xdd, 0xda, 0xf2, 0xa1, 0xc3, 0xf8, 0x26, 0x4a,
	0x05, 0x4f, 0x66, 0x3c, 0x79, 0xe5, 0x09, 0xc1, 0x80, 0xd2, 0x68, 0x6d, 0x1a, 0x77, 0xc6, 0x7d,
	0x9d, 0xc9, 0x4f, 0x62, 0x42, 0xe3, 0x95, 0x27, 0x69, 0x14, 0xef, 0xcc, 0x5a, 0x5e, 0x2d, 0xa4,
	0x9c, 0x15, 0xd1, 0xda, 0x44, 0x6a, 0x56, 0x44, 0x6b, 0x4b, 0x40, 0xdb, 0x8b, 0x37, 0xd1, 0xce,
	0xce, 0xc4, 0x0b, 0xe3, 0x7b, 0x39, 0x91, 0x55, 0xd7, 0xb2, 0x68, 0x5d, 0xec, 0xd4, 0xca, 0x9d,
	0x82, 0x88, 0x4e, 0x12, 0xcf, 0x8f, 0x89, 0x3d, 0xa8, 0x6f, 0x85, 0xcb, 0xff, 0x98, 0xf5, 0x3b,
	0xe3, 0xbe, 0xc5, 0x94, 0xb0, 0xbe, 0x1f, 0x51, 0x53, 0x62, 0x01, 0x4a, 0xb8, 0xc8, 0xa9, 0x9d,
	0x07, 0x3c, 0xd0, 0x61, 0x07, 0xaa, 0x2d, 0x98, 0x6c, 0x16, 0xd4, 0xda, 0x49, 0x2a, 0x3a, 0xa2,
	0x5a, 0x3f, 0xa0, 0x99, 0xdf, 0xd7, 0x89, 0x44, 0x95, 0x48, 0xfb, 0xcf, 0xaa, 0x4b, 0x32, 0x63,
	0xe9, 0x12, 0x1d, 0xb8, 0x24, 0xef, 0xa1, 0xf9, 0x6b, 0xb9, 0xdb, 0x64, 0xcb, 0x0d, 0xcf, 0x63,
	0xb5, 0x58, 0xa9, 0xad, 0xb8, 0x24, 0xa4, 0xe4, 0xc3, 0xa1, 0xfb, 0x6e, 0xe9, 0x5e, 0xf7, 0x2b,
	0xfb, 0x27, 0xa0, 0xf1, 0x4e, 0x43, 0x11, 0x53, 0x82, 0xbc, 0x81, 0x8b, 0xd5, 0x0b, 0xdf, 0x67,
	0x0a, 0x89, 0x98, 0x56, 0xd6, 0x27, 0x68, 0x79, 0xf1, 0x26, 0xce, 0x84, 0x24, 0x7e, 0x3c, 0x24,
	0x92, 0x43, 0x62, 0x3e, 0xa0, 0x90, 0x7d, 0x1b, 0x1a, 0xfa, 0x05, 0xc9, 0x25, 0x34, 0xec, 0x30,
	0x18, 0x2f, 0xa8, 0x8b, 0xcf, 0xa4, 0xf0, 0xe9, 0x22, 0x98, 0x4f, 0x1d, 0x6c, 0x90, 0x2b, 0x68,
	0xf9, 0x74, 0x31, 0x73, 0xd8, 0x57, 0x87, 0xe1, 0x9a, 0x94, 0xae, 0x33, 0x5f, 0x38, 0x8c, 0x51,
	0x86, 0x51, 0xff, 0xaf, 0x51, 0xe6, 0x14, 0xa4, 0x0d, 0x4d, 0x8f, 0x8e, 0x26, 0xbe, 0xba, 0x72,
	0x03, 0xd7, 0x4a, 0x55, 0xf3, 0x06, 0x79, 0x0b, 0x37, 0xaa, 0x28, 0xa7, 0x82, 0xb1, 0xc3, 0x16,
	0x23, 0xfb, 0x8b, 0x83, 0x6b, 0xe4, 0x1d, 0xdc, 0xfe, 0xd7, 0xd0, 0x48, 0x54, 0xed, 0xd8, 0xc3,
	0x21, 0x0d, 0xfd, 0x40, 0x1f, 0x3b, 0xaf, 0x76, 0x8a, 0xc6, 0xa3, 0x47, 0x87, 0xae, 0xf3, 0x84,
	0xeb, 0xe4, 0x16, 0xba, 0xaa, 0x15, 0xd8, 0x8f, 0x9e, 0xa3, 0x37, 0x2e, 0x48, 0x0f, 0xb0, 0x2e,
	0xcf, 0xa7, 0x45, 0xb5, 0x71, 0xc2, 0xd4, 0xcc, 0xa3, 0x01, 0x6e, 0x12, 0x13, 0x7a, 0xaa, 0xe1,
	0xd9, 0xfe, 0x28, 0xb4, 0x47, 0xc5, 0x4a, 0xab, 0xbf, 0xaf, 0x5e, 0x3b, 0xcf, 0x1d, 0xfa, 0xae,
	0x4f, 0xbf, 0xf9, 0x0f, 0xf8, 0x4c, 0xbe, 0x90, 0x47, 0x47, 0x34, 0x0c, 0xe4, 0x33, 0x18, 0x84,
	0x40, 0xa7, 0x90, 0xcf, 0xcf, 0xde, 0xc4, 0x97, 0x61, 0xbb, 0x70, 0xa5, 0x6b, 0xe1, 0xf4, 0xc9,
	0x0e, 0x1c, 0x8c, 0xc8, 0x35, 0x5c, 0xea, 0x92, 0x3b, 0x19, 0xba, 0xf8, 0xfc, 0xa0, 0x30, 0x1c,
	0x4f, 0xa6, 0xb8, 0xfe, 0xf3, 0x22, 0xff, 0xd3, 0x3f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0x76, 0x81, 0xcf, 0xf9, 0x03, 0x00, 0x00,
}
